### ISSUE TITLE
[packaging] tracking status for workspace images

### ISSUE THREAD

**Issue by ajhalili2006** [gitpodify/workspace-images#5]
## About this issue

We use this meta issue as Image Building Dashboard, similar to the [Dependency Dashboard](https://github.com/gitpodify/workspace-images/issues/3) to centralize work on adding packages as well as tracking image builds.

### Combinations

* [x] base
* [ ] `dock.mau.dev/recaptime-dev/docker/devenv` - meta dev env image for @recaptime-dev
* [ ] full - similar to `gitpod/workspace-full`, but TBD

### Tools, Languages and other packages

* [x] docker
* [x] tailscale
* [ ] #6
* [ ] https://github.com/gitpodify/workspace-images/issues/4
